import type { ScannerSnapshot } from "@/lib/queries/scanner-snapshot";
import type { StrategyCandidate } from "@/lib/engines/strategy-engine";

export function buildCopyTradeIdeaText(
  c: StrategyCandidate,
  snap: Pick<ScannerSnapshot, "portfolioValue" | "mode">,
): string {
  const lines: string[] = [];
  lines.push(`Trade idea (simulated — verify before placing real orders)`);
  lines.push(`Symbol: ${c.symbol} · ${c.assetType} · Mode: ${snap.mode}`);
  lines.push(`Confidence ${c.confidence.toFixed(1)} · Risk score ${c.riskScore.toFixed(1)}`);
  lines.push(`Strategy: ${c.strategyTag.replace(/_/g, " ")} · View: ${c.strategyViewTag.replace(/_/g, " ")}`);
  lines.push("");
  lines.push(`Thesis: ${c.thesis}`);
  lines.push("");
  lines.push(`Catalyst: ${c.catalystSummary}`);
  lines.push(`Hold: ${c.holdingPeriodNote}`);
  lines.push(`Invalidation (what would break the idea): ${c.invalidation}`);
  lines.push("");
  lines.push(
    `Sizing note: proposed notional ~$${Math.round(c.proposedNotional).toLocaleString()} vs book ~$${Math.round(snap.portfolioValue).toLocaleString()} (simulator only).`,
  );
  if (c.stopPrice != null) {
    lines.push(`Stop reference (simulated): ${c.stopPrice.toFixed(2)}`);
  }
  lines.push(`Target / execution note: ${c.targetNote}`);
  lines.push("");
  lines.push(`Copy generated by Earnings Pilot AI scanner — not financial advice.`);

  return lines.join("\n");
}
